version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    extra_hosts:
      - "host.docker.internal:host-gateway" # 允许 Kafka 访问 Docker 主机的 IP，用于 Flink 连接 MySQL

  jobmanager:
    image: apache/flink:1.18.1
    container_name: flink-jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    extra_hosts:
      - "host.docker.internal:host-gateway" # 允许 Flink 访问 Docker 主机的 IP，用于 Flink 连接 MySQL

  taskmanager:
    image: apache/flink:1.18.1
    container_name: flink-taskmanager
    hostname: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 # 根据需要调整
    extra_hosts:
      - "host.docker.internal:host-gateway" # 允许 Flink 访问 Docker 主机的 IP，用于 Flink 连接 MySQL